### ISSUE TITLE
[Sample] Missing audio segment

### ISSUE THREAD

**Issue by shinchiro** [tp7/Sushi#14]
If you're searching for the sample, you can try this :)
http://www.datafilehost.com/d/5c5d685f

the full audio is bd while the dvd is cut at the OP song (beginning) & ED song (ending), though the dvd is ntsc type. I hope that doesnt really affect it

**Comment by tp7** [comment]
Thanks.
I'll need the script too, although I'm afraid that different framerate might prevent me from using this sample.

**Comment by shinchiro** [comment]
Here:
http://pastebin.com/DJEUi6Pb

both sample has same framerate, 23.976 fps

**Comment by shinchiro** [comment]
Another sample:
http://www.datafilehost.com/d/22068439

one sample has tv promo after op, while other doesnt has

**Comment by tp7** [comment]
Hi, thanks for the samples.

Unfortunately you're missing the point here - the problem I'm trying to fix is when there's some segments in the original audio that are not present in the destination stream. For example there's a scene in TV broadcast that got replaced/cut out on blurays. 

On your samples sushi works correctly out of the box (with --window 100 for the first sample) because all source lines are actually present in the destination.

Of course I could easily fake a sample using the files you provided to fix it, but at this point I'm really not sure if the issue is common enough in real world hence worth fixing, so I'm waiting for people to report *real* issues with it.

**Comment by shinchiro** [comment]
I just working the sample what you mean. Some dialogue in source (tv) got replaced in destination (bd). Still, sushi able to recover from that error as usual when I used --window 100. But the absent line in bd scattered randomly, so I thought if it can put non-existent line in the end of ass file will be great

Here's shifting longs:
http://pastebin.com/P9C5Q0zB
